
flowchart LR
    Vedtak["Vedtak"] --> Engangsbeløp_GEBYR_SKYLDNER_NAV["Engangsbeløp Gebyr skyldner"]
    Engangsbeløp_GEBYR_SKYLDNER_NAV["Engangsbeløp Gebyr skyldner"] --> SLUTTBEREGNING_GEBYR_BIDRAGSPLIKTIG["SLUTTBEREGNING_GEBYR_BIDRAGSPLIKTIG"]
    Vedtak["Vedtak"] --> Engangsbeløp_GEBYR_MOTTAKER_NAV["Engangsbeløp Gebyr mottaker"]
    Engangsbeløp_GEBYR_MOTTAKER_NAV["Engangsbeløp Gebyr mottaker"] --> SLUTTBEREGNING_GEBYR_PERSON_BIDRAGSMOTTAKER["SLUTTBEREGNING_GEBYR_BIDRAGSMOTTAKER"]


    subgraph Delberegning

        SLUTTBEREGNING_GEBYR_PERSON_BIDRAGSMOTTAKER --> sjablon_FastsettelsesgebyrBeløp_202501["Sjablon(FASTSETTELSESGEBYR_BELØP)"]
        DELBEREGNING_INNTEKTSBASERT_GEBYR_BIDRAGSMOTTAKER["DELBEREGNING_INNTEKTSBASERT_GEBYR_BIDRAGSMOTTAKER"] --> sjablon_NedreInntektsgrenseGebyrBeløp["Sjablon(NEDRE_INNTEKTSGRENSE_GEBYR_BELØP)"]
        DELBEREGNING_INNTEKTSBASERT_GEBYR_BIDRAGSMOTTAKER[["DELBEREGNING_INNTEKTSBASERT_GEBYR_BIDRAGSMOTTAKER"]] --> delberegning_DELBEREGNING_SUM_INNTEKT_BIDRAGSMOTTAKER["Delberegning sum inntekt bidragsmottaker"]
        SLUTTBEREGNING_GEBYR_PERSON_BIDRAGSMOTTAKER --> DELBEREGNING_INNTEKTSBASERT_GEBYR_BIDRAGSMOTTAKER["DELBEREGNING_INNTEKTSBASERT_GEBYR_BIDRAGSMOTTAKER"]
        SLUTTBEREGNING_GEBYR_BIDRAGSPLIKTIG --> sjablon_FastsettelsesgebyrBeløp["Sjablon(FASTSETTELSESGEBYR_BELØP)"]
        SLUTTBEREGNING_GEBYR_BIDRAGSPLIKTIG --> MANUELT_OVERSTYRT_GEBYR_BIDRAGSPLIKTIG["MANUELT_OVERSTYRT_GEBYR_BIDRAGSPLIKTIG"]
        SLUTTBEREGNING_GEBYR_BIDRAGSPLIKTIG --> DELBEREGNING_INNTEKTSBASERT_GEBYR_BIDRAGSPLIKTIG["DELBEREGNING_INNTEKTSBASERT_GEBYR_BIDRAGSPLIKTIG"]
    end


