---
config:
  class:
    hideEmptyMembersBox: true
---

classDiagram
    direction LR
    class Vedtak
    class Engangsbeløp_GEBYR_SKYLDNER_NAV {
    }
    class Engangsbeløp_GEBYR_MOTTAKER_NAV {
    }
    namespace Bidragspliktig {
        class SLUTTBEREGNING_GEBYR_BIDRAGSPLIKTIG {
        }
        class MANUELT_OVERSTYRT_GEBYR_BIDRAGSPLIKTIG {
        }
        class DELBEREGNING_INNTEKTSBASERT_GEBYR_BIDRAGSPLIKTIG {
        }
        class delberegning_DELBEREGNING_SUM_INNTEKT_BIDRAGSPLIKTIG {
        }
        class PERSON_BIDRAGSPLIKTIG {
        }
    }
    namespace Bidragsmottaker {
        class PERSON_BIDRAGSMOTTAKER {
        }
        class SLUTTBEREGNING_GEBYR_BIDRAGSMOTTAKER {
        }
        class DELBEREGNING_INNTEKTSBASERT_GEBYR_BIDRAGSMOTTAKER {
        }
        class delberegning_DELBEREGNING_SUM_INNTEKT_BIDRAGSMOTTAKER {
        }
    }

    class sjablon_FastsettelsesgebyrBeløp {
    }

    class sjablon_NedreInntektsgrenseGebyrBeløp {
    }

    Vedtak --> Engangsbeløp_GEBYR_SKYLDNER_NAV
    Engangsbeløp_GEBYR_SKYLDNER_NAV --> SLUTTBEREGNING_GEBYR_BIDRAGSPLIKTIG
    Vedtak --> Engangsbeløp_GEBYR_MOTTAKER_NAV
    Engangsbeløp_GEBYR_MOTTAKER_NAV --> SLUTTBEREGNING_GEBYR_BIDRAGSMOTTAKER

    class Delberegning {
    }
    Delberegning: - DELBEREGNING_INNTEKTSBASERT_GEBYR_BIDRAGSMOTTAKER
    Delberegning: - delberegning_DELBEREGNING_SUM_INNTEKT_BIDRAGSMOTTAKER
    Delberegning: - sjablon_FastsettelsesgebyrBeløp
    Delberegning: - PERSON_BIDRAGSMOTTAKER
    Delberegning: - sjablon_NedreInntektsgrenseGebyrBeløp

    class Delberegning_manuelt {
    }
    Delberegning_manuelt: - MANUELT_OVERSTYRT_GEBYR_BIDRAGSPLIKTIG
    Delberegning_manuelt: - DELBEREGNING_INNTEKTSBASERT_GEBYR_BIDRAGSPLIKTIG
    Delberegning_manuelt: - delberegning_DELBEREGNING_SUM_INNTEKT_BIDRAGSPLIKTIG
    Delberegning_manuelt: - sjablon_FastsettelsesgebyrBeløp
    Delberegning_manuelt: - PERSON_BIDRAGSPLIKTIG
    SLUTTBEREGNING_GEBYR_BIDRAGSMOTTAKER --> DELBEREGNING_INNTEKTSBASERT_GEBYR_BIDRAGSMOTTAKER
    DELBEREGNING_INNTEKTSBASERT_GEBYR_BIDRAGSMOTTAKER --> delberegning_DELBEREGNING_SUM_INNTEKT_BIDRAGSMOTTAKER
    SLUTTBEREGNING_GEBYR_BIDRAGSMOTTAKER --> sjablon_FastsettelsesgebyrBeløp
    SLUTTBEREGNING_GEBYR_BIDRAGSMOTTAKER --> PERSON_BIDRAGSMOTTAKER
    DELBEREGNING_INNTEKTSBASERT_GEBYR_BIDRAGSMOTTAKER --> sjablon_NedreInntektsgrenseGebyrBeløp
    SLUTTBEREGNING_GEBYR_BIDRAGSPLIKTIG --> MANUELT_OVERSTYRT_GEBYR_BIDRAGSPLIKTIG
    SLUTTBEREGNING_GEBYR_BIDRAGSPLIKTIG --> DELBEREGNING_INNTEKTSBASERT_GEBYR_BIDRAGSPLIKTIG
    DELBEREGNING_INNTEKTSBASERT_GEBYR_BIDRAGSPLIKTIG --> delberegning_DELBEREGNING_SUM_INNTEKT_BIDRAGSPLIKTIG
    SLUTTBEREGNING_GEBYR_BIDRAGSPLIKTIG --> sjablon_FastsettelsesgebyrBeløp
    SLUTTBEREGNING_GEBYR_BIDRAGSPLIKTIG --> PERSON_BIDRAGSPLIKTIG
    DELBEREGNING_INNTEKTSBASERT_GEBYR_BIDRAGSPLIKTIG --> sjablon_NedreInntektsgrenseGebyrBeløp


click SLUTTBEREGNING_GEBYR_BIDRAGSPLIKTIG call visGrunnlag("grunnlagsobjekter/gebyr/sluttberegning_gebyr.md")