flowchart LR
ikke_referert[["Frittstående(Ikke refert av grunnlag eller stønadsendring/engangsbeløp)"]] -.- innhentet_husstandsmedlem_person_PERSON_BIDRAGSMOTTAKER_19660507_920_person_PERSON_HUSSTANDSMEDLEM_20150704_innhentet_1586044995["Innhentet husstandsmedlem(04.07.2015)"]
ikke_referert[["Frittstående(Ikke refert av grunnlag eller stønadsendring/engangsbeløp)"]] -.- innhentet_husstandsmedlem_person_PERSON_BIDRAGSMOTTAKER_19660507_920_person_PERSON_HUSSTANDSMEDLEM_19791011_innhentet_-879930728["Innhentet husstandsmedlem(11.10.1979)"]
ikke_referert[["Frittstående(Ikke refert av grunnlag eller stønadsendring/engangsbeløp)"]] -.- innhentet_husstandsmedlem_person_PERSON_BIDRAGSMOTTAKER_19660507_920_person_PERSON_HUSSTANDSMEDLEM_19790822_innhentet_314312783["Innhentet husstandsmedlem(22.08.1979)"]
ikke_referert[["Frittstående(Ikke refert av grunnlag eller stønadsendring/engangsbeløp)"]] -.- innhentet_husstandsmedlem_person_PERSON_BIDRAGSMOTTAKER_19660507_920_person_PERSON_HUSSTANDSMEDLEM_20170723_innhentet_1143191584["Innhentet husstandsmedlem(23.07.2017)"]
ikke_referert[["Frittstående(Ikke refert av grunnlag eller stønadsendring/engangsbeløp)"]] -.- innhentet_husstandsmedlem_person_PERSON_BIDRAGSMOTTAKER_19660507_920_person_PERSON_HUSSTANDSMEDLEM_20051027_innhentet_-1402622917["Innhentet husstandsmedlem(27.10.2005)"]
Vedtak["Vedtak"] --> Stønadsendring_FORSKUDD_26431698667["Stønadsendring Barn 1"]
subgraph PERSON
direction LR
person_PERSON_SØKNADSBARN_20160326_919["PERSON_SØKNADSBARN(26.03.2016)"]
person_PERSON_BIDRAGSMOTTAKER_19660507_920["PERSON_BIDRAGSMOTTAKER(07.05.1966)"]
person_PERSON_HUSSTANDSMEDLEM_20180223_1058["PERSON_HUSSTANDSMEDLEM(23.02.2018)"]
person_PERSON_HUSSTANDSMEDLEM_20051027_innhentet_-1402622917["PERSON_HUSSTANDSMEDLEM(27.10.2005)"]
person_PERSON_HUSSTANDSMEDLEM_20170723_innhentet_1143191584["PERSON_HUSSTANDSMEDLEM(23.07.2017)"]
person_PERSON_HUSSTANDSMEDLEM_19790822_innhentet_314312783["PERSON_HUSSTANDSMEDLEM(22.08.1979)"]
person_PERSON_HUSSTANDSMEDLEM_19791011_innhentet_-879930728["PERSON_HUSSTANDSMEDLEM(11.10.1979)"]
person_PERSON_HUSSTANDSMEDLEM_20150704_innhentet_1586044995["PERSON_HUSSTANDSMEDLEM(04.07.2015)"]
end
subgraph ANDRE
direction LR
virkningstidspunkt["virkningstidspunkt"]
søknad["søknad"]
end
subgraph Delberegning
sivilstand_person_PERSON_BIDRAGSMOTTAKER_19660507_920_20250101["Sivilstand(Bor alene med barn/01.2025)"] --> innhentet_sivilstand_person_PERSON_BIDRAGSMOTTAKER_19660507_920["Innhentet sivilstand (Alle)"]
delberegning_DELBEREGNING_SUM_INNTEKT_person_PERSON_BIDRAGSMOTTAKER_19660507_920_person_PERSON_SØKNADSBARN_20160326_919_202501["Delberegning sum inntekt bidragsmottaker (01.2025)"] --> inntekt_UTVIDET_BARNETRYGD_person_PERSON_BIDRAGSMOTTAKER_19660507_920_20250101_3121["Utvidet barnetrygd (manuelt registrert)"]
delberegning_DELBEREGNING_SUM_INNTEKT_person_PERSON_BIDRAGSMOTTAKER_19660507_920_person_PERSON_SØKNADSBARN_20160326_919_202501["Delberegning sum inntekt bidragsmottaker (01.2025)"] --> inntekt_LØNN_MANUELT_BEREGNET_person_PERSON_BIDRAGSMOTTAKER_19660507_920_20250101_3119["Lønn manuelt beregnet (manuelt registrert)"]
delberegning_DELBEREGNING_SUM_INNTEKT_person_PERSON_BIDRAGSMOTTAKER_19660507_920_person_PERSON_SØKNADSBARN_20160326_919_202501["Delberegning sum inntekt bidragsmottaker (01.2025)"] --> inntekt_KONTANTSTØTTE__person_PERSON_BIDRAGSMOTTAKER_19660507_920_ba_person_PERSON_SØKNADSBARN_20160326_919_20250101_3122["Kontantstøtte (manuelt registrert)"]
delberegning_DELBEREGNING_SUM_INNTEKT_person_PERSON_BIDRAGSMOTTAKER_19660507_920_person_PERSON_SØKNADSBARN_20160326_919_202501["Delberegning sum inntekt bidragsmottaker (01.2025)"] --> inntekt_BARNETILLEGG_BARNETILLEGG_PENSJON_person_PERSON_BIDRAGSMOTTAKER_19660507_920_ba_person_PERSON_SØKNADSBARN_20160326_919_20250101_3120["Barnetillegg (manuelt registrert)"]
bostatus_person_PERSON_SØKNADSBARN_20160326_919_20250101["Bosstatus søknadsbarn (Registrert på adresse/01.2025})"] --> innhentet_husstandsmedlem_person_PERSON_BIDRAGSMOTTAKER_19660507_920_person_PERSON_SØKNADSBARN_20160326_919["Innhentet husstandsmedlem(26.03.2016)"]
delberegning_DELBEREGNING_BARN_I_HUSSTAND_person_PERSON_BIDRAGSMOTTAKER_19660507_920_person_PERSON_SØKNADSBARN_20160326_919_202501["Delberegning barn i husstand(01.2025)"] --> bostatus_person_PERSON_SØKNADSBARN_20160326_919_20250101["Bosstatus søknadsbarn (Registrert på adresse/01.2025})"]
bostatus_person_PERSON_HUSSTANDSMEDLEM_20180223_1058_20250101["Bosstatus husstandsmedlem (Registrert på adresse/01.2025})"] --> innhentet_husstandsmedlem_person_PERSON_BIDRAGSMOTTAKER_19660507_920_person_PERSON_HUSSTANDSMEDLEM_20180223_1058["Innhentet husstandsmedlem(23.02.2018)"]
delberegning_DELBEREGNING_BARN_I_HUSSTAND_person_PERSON_BIDRAGSMOTTAKER_19660507_920_person_PERSON_SØKNADSBARN_20160326_919_202501["Delberegning barn i husstand(01.2025)"] --> bostatus_person_PERSON_HUSSTANDSMEDLEM_20180223_1058_20250101["Bosstatus husstandsmedlem (Registrert på adresse/01.2025})"]
end
subgraph Stønadsendring_Stønadsendring Barn 1
sluttberegning_person_PERSON_SØKNADSBARN_20160326_919_202501["Sluttberegning(01.2025)"] --> sjablon_ØvreInntektsgrenseFulltForskuddBeløp_202407["Sjablon(ØVRE_INNTEKTSGRENSE_FULLT_FORSKUDD_BELØP)"]
sluttberegning_person_PERSON_SØKNADSBARN_20160326_919_202501["Sluttberegning(01.2025)"] --> sjablon_ØvreInntektsgrense75ProsentForskuddGSBeløp_202407["Sjablon(ØVRE_INNTEKTSGRENSE_75PROSENT_FORSKUDD_GS_BELØP)"]
sluttberegning_person_PERSON_SØKNADSBARN_20160326_919_202501["Sluttberegning(01.2025)"] --> sjablon_ØvreInntektsgrense75ProsentForskuddEnBeløp_202407["Sjablon(ØVRE_INNTEKTSGRENSE_75PROSENT_FORSKUDD_EN_BELØP)"]
sluttberegning_person_PERSON_SØKNADSBARN_20160326_919_202501["Sluttberegning(01.2025)"] --> sjablon_MaksInntektForskuddMottakerMultiplikator_202307["Sjablon(MAKS_INNTEKT_FORSKUDD_MOTTAKER_MULTIPLIKATOR)"]
sluttberegning_person_PERSON_SØKNADSBARN_20160326_919_202501["Sluttberegning(01.2025)"] --> sjablon_InntektsintervallForskuddBeløp_202407["Sjablon(INNTEKTSINTERVALL_FORSKUDD_BELØP)"]
sluttberegning_person_PERSON_SØKNADSBARN_20160326_919_202501["Sluttberegning(01.2025)"] --> sjablon_ForskuddssatsBeløp_202407["Sjablon(FORSKUDDSSATS_BELØP)"]
sluttberegning_person_PERSON_SØKNADSBARN_20160326_919_202501["Sluttberegning(01.2025)"] --> sjablon_Forskuddssats75ProsentBeløp_202407["Sjablon(FORSKUDDSSATS_75PROSENT_BELØP)"]
sluttberegning_person_PERSON_SØKNADSBARN_20160326_919_202501["Sluttberegning(01.2025)"] --> sivilstand_person_PERSON_BIDRAGSMOTTAKER_19660507_920_20250101["Sivilstand(Bor alene med barn/01.2025)"]
sluttberegning_person_PERSON_SØKNADSBARN_20160326_919_202501["Sluttberegning(01.2025)"] --> |"Delberegning sum inntekt bidragsmottaker (01.2025)"| delberegning_DELBEREGNING_SUM_INNTEKT_person_PERSON_BIDRAGSMOTTAKER_19660507_920_person_PERSON_SØKNADSBARN_20160326_919_202501[["Delberegning sum inntekt bidragsmottaker (01.2025)"]]
sluttberegning_person_PERSON_SØKNADSBARN_20160326_919_202501["Sluttberegning(01.2025)"] --> |"Delberegning barn i husstand(01.2025)"| delberegning_DELBEREGNING_BARN_I_HUSSTAND_person_PERSON_BIDRAGSMOTTAKER_19660507_920_person_PERSON_SØKNADSBARN_20160326_919_202501[["Delberegning barn i husstand(01.2025)"]]
sluttberegning_person_PERSON_SØKNADSBARN_20160326_919_202501["Sluttberegning(01.2025)"] --> bostatus_person_PERSON_SØKNADSBARN_20160326_919_20250101["Bosstatus søknadsbarn (Registrert på adresse/01.2025})"]
Periode01.202526431698667[["Periode(01.2025)"]] --> sluttberegning_person_PERSON_SØKNADSBARN_20160326_919_202501
end